# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: CmdLine@2
      inputs:
        script: tree $(Agent.WorkFolder)\1 /f
    - task: Docker@2
      inputs:
        containerRegistry: 'pranilocal docker hub'
        repository: 'pranilocal/weatherapi'
        command: 'buildAndPush'
        Dockerfile: '**/DockerFile'
        tags: |
          $(tag)
- stage: Provision
  displayName: "Terraforming on Azure.."
  dependsOn: Build
  jobs:
  - job: Provision
    displayName: "Provision Container Instance"
    pool:
      vmImage: 'ubuntu-latest'
    variables:
    - group: Terraform Creds
    steps:
    - script: |
        set -e

        terraform init -input=false
        terraform apply -input=false -auto-approve
      name: 'RunTerraform'
      displayName: 'Run Terraform'
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        TF_VAR_tfimagevers: $(tag)